# -*- mode: python ; coding: utf-8 -*-
#
# Auto-generated by build.py
# Bundle mode: onedir

from pathlib import Path
import sys

from PyInstaller.utils.hooks import collect_submodules, copy_metadata
import PySide6
import pymavlink

block_cipher = None

project_root = Path(SPECPATH).resolve()
src_dir = project_root / "src"
sys.path.insert(0, str(src_dir))
sys.path.insert(0, str(project_root))

from build import pymavlink_bundle_data


def existing_data(rel_path: str, dest: str):
    path = (project_root / rel_path).resolve()
    if not path.exists():
        return []
    return [(str(path), dest)]


icon_path = None

# Qt 6.11 wheels are built against a newer MSVC runtime than some Python
# distributions bundle.  Supplying the wheel's matching runtime at the
# executable root prevents Windows from resolving an older VCRUNTIME first.
pyside_root = Path(PySide6.__file__).resolve().parent
qt_msvc_runtime_names = ('MSVCP140.dll', 'MSVCP140_1.dll', 'MSVCP140_2.dll', 'VCRUNTIME140.dll', 'VCRUNTIME140_1.dll')
qt_msvc_binaries = [
    (str(pyside_root / name), ".")
    for name in qt_msvc_runtime_names
    if (pyside_root / name).is_file()
]

datas = []
datas += existing_data("assets", "assets")
datas += existing_data("config", "config")
datas += existing_data("README.md", ".")
datas += pymavlink_bundle_data(Path(pymavlink.__file__).resolve().parent)

for package_name in ("PySide6", "pyqtgraph", "numpy", "scipy", "polars", "pyulog", "rosbags", "pymavlink", "PyYAML"):
    try:
        datas += copy_metadata(package_name)
    except Exception:
        pass

hiddenimports = []
for module_name in (
    "analysis",
    "core",
    "engines",
    "gui",
    "storage",
    "visualization",
    "readers",
    "pyulog",
    "rosbags",
):
    try:
        hiddenimports += collect_submodules(module_name)
    except Exception:
        pass

hiddenimports += [
    "pyqtgraph.exporters",
    "pyqtgraph.exporters.ImageExporter",
    "scipy.interpolate",
    "scipy.signal",
    "yaml",
    "pymavlink.DFReader",
    "pymavlink.mavutil",
    *('pymavlink.dialects.v10.all', 'pymavlink.dialects.v20.all', 'pymavlink.dialects.v10.ardupilotmega', 'pymavlink.dialects.v20.ardupilotmega'),
]
hiddenimports = sorted(set(hiddenimports))

excludes = [
    "IPython",
    "jupyter",
    "jupyter_client",
    "jupyter_core",
    "matplotlib",
    "matplotlib.tests",
    "nbformat",
    "numpy.tests",
    "pandas",
    "pandas.tests",
    "pytest",
    "tests",
    "tkinter",
    "zmq",
]

a = Analysis(
    [str(src_dir / "main.py")],
    pathex=[str(src_dir), str(project_root)],
    binaries=qt_msvc_binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excludes,
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='Log ansys',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    contents_directory=".",
    icon=icon_path,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='Log ansys',
)

